// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwdmdpzodefrfwwpfrjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3ZG1kcHpvZGVmcmZ3d3BmcmpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTY0MTgsImV4cCI6MjA2NTQ5MjQxOH0.2EssD7ozk4jbh8KqPQG_kkasdxTpRGSBCDk4zOgid3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);